# Generated by Django 5.0.2 on 2024-02-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsview',
            name='dysplay_on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
