# Generated by Django 5.0.2 on 2024-02-28 00:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsview_dysplay_on_main_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsView',
            new_name='ProductsModel',
        ),
    ]
