# Generated by Django 5.0.2 on 2024-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categorymodel_categoryproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
